### ISSUE TITLE
Make initial fall run to winter run translation

### ISSUE THREAD

**Issue by ergz** [CVPIA-OSC/winterRunDSM#1]
- [x] Change namings: README, DESCRIPTION file, main function name (and any docs, dependencies or other scripts)
- [x] Cached data - make loadbaseline data take care of any winter run specific datasets 
- [x] Cached data script - incorporate values based on the OG winter run model
- [x] Betas - find and replace fall run betas with appropriate winter run betas 
- [x] Timing - find the difference in timing between FR and WR, change where appropriate (take notes if want to pair program)
       I made the changes in the comment below. 
- [x] Make note of other differences between the models for review

**Comment by ErinCain** [comment]
Notes on line by line timing changes:
- [x] LINE 85 New Model: Old Month 1:8 loop --> Change to month `c(9:12), c(1:5)` loop (OG model line 1033) 
- [x] LINE 91 New Model: Old Month == 8 --> Change to month == 5 (OG model doesn't really do it like this...they just add all the outmigrate at the end but think we still want to send them all out in last month) 
- [x] Get_Habitat.R New Model: Old Month < 4 fry vs. juv... --> change to month > 8 (OG model line 1044)
- [x] LINE 224 route_and_rear_deltas: if month == 8 and if month != 8 --> change to month == 5 and month != 5
- [x] LINE 205 `survival.R`: Stranding probabilities old if month < 4  --> change `if (month > 8)` use prob strand early  else use prob strand late  (OG model line 1053)

**Comment by ErinCain** [comment]
Notes on other differences between models to review: 
- [x] Do not use straying in winterRunDSM (check this out and change in new model) 
- [x] Degree Day logic: There is a spawn time triangular distribution that we need to account for in Degree days calculation as well as other changes we made for springRunDSM
- [x] We will need to create a `juvenile_dynamics_year` and all update the model code to use `juvenile_dynamics_year`
